### ISSUE TITLE
Your Device's iOS version is not supported at this time!!!

### ISSUE THREAD

**Issue by wjiao119** [master131/iFakeLocation#167]
Dear All, I get the same error message, don't know how to resolve it. I am using windows (laptop), Window 10 pro. How to resolve this? It happens to suddenly, very strange. It used to work well, now not working at all. 
![image](https://github.com/master131/iFakeLocation/assets/73743555/baf9862f-1d1f-4b52-aa7d-adb026c9fceb)

**Comment by TimVGithub** [comment]
iOS 17 is not currently supported

Issue #141  has the details

**Comment by ewandank** [comment]
Hi, I encounted the issue to this on ios 15.8 as well. Downloading the 15.7 image manually and then renaming it 15.8 did the trick. 
i.e download the image zip from [here](https://github.com/master131/iFakeLocation/releases/download/v1.6.0/iPhone-iPadOS-15.7.zip) and extract it in the `DeveloperImages` and rename the folder to 15.8. Worked fine for me after that. I will open a pr to resolve this issue.

**Comment by wjiao119** [comment]
Hi Thanks for your message. I am using windows laptop to lock the fuel voucher. So which folder should I use? I can only see the folder and file information as below. Any further suggestion? Thanks.

[cid:a4493ebc-cee3-4647-aeca-58bc28605616]

kind regards,
________________________________

**Comment by Prabh-Saini** [comment]
Hey, if you were using iFakeLocation on iOS 15.7, go to your iFakeLocation folder which has the app inside, then open the folder "DeveloperImages" inside. There should be a folder called "15.7", copy and paste it (so that the folder is duplicated), then with the new folder rename it EXACTLY to "15.8". Then you can use iFakeLocation again like normal.

**Comment by wjiao119** [comment]
Hi, thanks for looking into my case. I am not sure if I understand you. I don't see any folder with a name of 15.7 or 15.8. Below is what I can see in the folder. Happy to discuss. Thanks.

[cid:5ef4a806-ffed-4ceb-a36c-dbf0b7b5fd85]
________________________________

**Comment by Prabh-Saini** [comment]
Hey sorry, you don't have an image attached. Anyway, where the iFakeLocation executable (the app) is, find the folder named "DeveloperImages" and there you will find the "15.7" folder, duplicate it and rename it to "15.8".

**Comment by wjiao119** [comment]
Hi Mate,

Thanks so much for reply my message. Sorry, Attached is the folder list. I don't know where to locate the folder you refer to. Please kindly advise. Thanks a lot.
________________________________

**Comment by ewandank** [comment]
It's the folder where you run iFakeLocation from, the zip folder that you should have extracted to run the `iFakeLocation.exe` file. I have attached a screeenshot of what it looks like on Linux. As said before, you need to look in the `DeveloperImages` folder and copy `15.7` to a new folder called `15.8`. If you don't have a `15.7` folder, you can download the `15.7` image from [here](https://github.com/master131/iFakeLocation/releases/download/v1.6.0/iPhone-iPadOS-15.7.zip) and extract it in the `DeveloperImages` folder and rename it `15.8`.
![image](https://github.com/master131/iFakeLocation/assets/101682978/d0c380b0-210c-44c3-940d-7eed96f51b31)

**Comment by wjiao119** [comment]
Thanks for your further message, mate. I am using windows. And I tried your suggestion, still not working. I create a folder and copy 15.7 files (from the link you shared) over to a new folder called 15.8 which is my iphone's version. Unfortunately, it is still not working. :( Do you have any further clue?
![image](https://github.com/master131/iFakeLocation/assets/73743555/721a40a9-d026-4c69-a789-93f7bc257dae)

**Comment by ewandank** [comment]
Apologies, you also need to create the `DevloperImages` Folder as well. 
The 15.8 folder should exist as follows: 
`ifakelocation-v1.7.0-windows-x86-x64/DeveloperImages/15.8`

**Comment by wjiao119** [comment]
Hi mate, you are genius. The problem is solved after following your instruction. Thanks so much.
________________________________

**Comment by zhkhan89** [comment]
> Apologies, you also need to create the `DevloperImages` Folder as well. The 15.8 folder should exist as follows: `ifakelocation-v1.7.0-windows-x86-x64/DeveloperImages/15.8`

Do you know how to go about Mac please? I dont have any Xcode as per some other comments seen. I have the Application itself in the Finder > Application > Show packaged contents. There is only BIN folder in there

**Comment by blakeASC5** [comment]
> Hi, I encounted the issue to this on ios 15.8 as well. Downloading the 15.7 image manually and then renaming it 15.8 did the trick. i.e download the image zip from [here](https://github.com/master131/iFakeLocation/releases/download/v1.6.0/iPhone-iPadOS-15.7.zip) and extract it in the `DeveloperImages` and rename the folder to 15.8. Worked fine for me after that. I will open a pr to resolve this issue.

So I tried following you instruction. I created 'DeveloperImages' download the IOSs 14.0 to 16.0 into the folder. Than I copied 15.7 and renamed it to 15.8 and went into the 15.7 folder and also renamed that folder 15.8. Is  there something I am doing wrong as I am still getting the error that my IOS is not compatible?

![issues](https://github.com/master131/iFakeLocation/assets/41080244/52ff2cdd-f7f7-4565-bbc6-6921b986d8ca)
![issues2](https://github.com/master131/iFakeLocation/assets/41080244/f9f2da68-78ea-492e-909b-c9ead8d2d361)
![issues3](https://github.com/master131/iFakeLocation/assets/41080244/56ea7c67-3606-4f92-b5e7-e669fe29224d)
