### ISSUE TITLE
iPadOS 14.4 not working

### ISSUE THREAD

**Issue by gyrex** [master131/iFakeLocation#46]
G'day mate, unfortunately I upgraded to iPadOS 14.4 and iFakeLocation says "Your device's iOS version is not supported at this time."

**Comment by gyrex** [comment]
Fixed it. Download the 14.4 xcode zip from here: https://github.com/alwynpan/xcode-developer-disk-image-all-platforms/raw/master/DiskImages/iPhoneOS.platform/DeviceSupport/14.4.zip

Then use the instructions in the wiki from here. The 14.4 xcode file isn't available in the github branch listed here.

**Comment by master131** [comment]
@gyrex Are you sure you are on the latest version of the app? It should be working on iOS 14.4 out of the box.

**Comment by gyrex** [comment]
> @gyrex Are you sure you are on the latest version of the app? It should be working on iOS 14.4 out of the box.

Yep, positive mate.

**Comment by macsir** [comment]
same here. (used the image above) Unable to mount developer image. Please update to 14.4. Thanks.

**Comment by gyrex** [comment]
> same here. (used the image above) Unable to mount developer image. Please update to 14.4. Thanks.

Use the link I provided above to download the files for 14.4 and use the intructions in the wiki here.

**Comment by macsir** [comment]
Yes, mate. I followed your instructions and still showing unable to mount.

**Comment by macsir** [comment]
Aha, it works after deleting the old images and let the app download it again.
